ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "linkedinUrl" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "whatsappNumber" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "resumeLink" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "resumeVaultUrl" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "panCardUrl" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "aadhaarUrl" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "bankDetailsUrl" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "notes" TEXT;
